
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int ROUTERS = 7;
  public static final int SHA = 8;
  public static final int DES = 3;
  public static final int EOL = 4;
  public static final int V2C = 11;
  public static final int STRING = 13;
  public static final int EOF = 0;
  public static final int AES = 2;
  public static final int NONE = 6;
  public static final int error = 1;
  public static final int MD5 = 5;
  public static final int V3 = 12;
  public static final int V1 = 10;
  public static final int SWITCHES = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AES",
  "DES",
  "EOL",
  "MD5",
  "NONE",
  "ROUTERS",
  "SHA",
  "SWITCHES",
  "V1",
  "V2C",
  "V3",
  "STRING"
  };
}

